CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    telegram_user_id BIGINT,
    chat_id BIGINT,
    username VARCHAR(255),
    first_name VARCHAR(255),
    phone_number VARCHAR(255),
    employee_code VARCHAR(255),
    full_name VARCHAR(255),
    department_name VARCHAR(255),
    unit_name VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_telegram_user_id UNIQUE (telegram_user_id),
    CONSTRAINT uk_users_phone_number UNIQUE (phone_number),
    CONSTRAINT uk_users_employee_code UNIQUE (employee_code),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE daily_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    report_date DATE NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_daily_reports PRIMARY KEY (id),
    CONSTRAINT fk_daily_reports_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_daily_reports_user_date_created
    ON daily_reports (user_id, report_date, created_at DESC);
