UPDATE users
SET employee_code = UPPER(TRIM(employee_code))
WHERE employee_code IS NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT ck_users_employee_code_normalized
        CHECK (employee_code IS NULL OR employee_code = UPPER(TRIM(employee_code)));

CREATE TABLE identity_admin_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    action VARCHAR(64) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    target_user_id BIGINT NOT NULL,
    related_user_id BIGINT,
    reason VARCHAR(1000) NOT NULL,
    before_state TEXT NOT NULL,
    after_state TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_identity_admin_audit PRIMARY KEY (id),
    CONSTRAINT fk_identity_admin_audit_target_user
        FOREIGN KEY (target_user_id) REFERENCES users (id),
    CONSTRAINT fk_identity_admin_audit_related_user
        FOREIGN KEY (related_user_id) REFERENCES users (id),
    CONSTRAINT ck_identity_admin_audit_action
        CHECK (action IN ('CREATE', 'UPDATE_PROFILE', 'REMAP_TELEGRAM', 'DEACTIVATE', 'REACTIVATE'))
);

CREATE INDEX idx_identity_admin_audit_target_created
    ON identity_admin_audit_events (target_user_id, created_at DESC);
