CREATE TABLE reminder_occurrences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    business_date DATE NOT NULL,
    state VARCHAR(32) NOT NULL,
    terminal_reason VARCHAR(64),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_reminder_occurrences PRIMARY KEY (id),
    CONSTRAINT fk_reminder_occurrences_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_reminder_occurrences_user_business_date
        UNIQUE (user_id, business_date),
    CONSTRAINT ck_reminder_occurrences_state
        CHECK (state IN ('PENDING', 'RETRY_ELIGIBLE', 'DELIVERED', 'FAILED', 'UNKNOWN', 'SUPPRESSED', 'EXPIRED')),
    CONSTRAINT ck_reminder_occurrences_terminal_reason
        CHECK (terminal_reason IS NULL OR terminal_reason IN (
            'MISSING_CHAT', 'TELEGRAM_REJECTED', 'UNKNOWN_TRANSPORT', 'NO_LONGER_DUE', 'FINAL_SLOT_EXPIRED'
        ))
);

CREATE TABLE reminder_delivery_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    occurrence_id BIGINT NOT NULL,
    attempt_number INTEGER NOT NULL,
    state VARCHAR(32) NOT NULL,
    failure_category VARCHAR(64),
    CONSTRAINT pk_reminder_delivery_attempts PRIMARY KEY (id),
    CONSTRAINT fk_reminder_delivery_attempts_occurrence
        FOREIGN KEY (occurrence_id) REFERENCES reminder_occurrences (id),
    CONSTRAINT uk_reminder_delivery_attempts_occurrence_number
        UNIQUE (occurrence_id, attempt_number),
    CONSTRAINT ck_reminder_delivery_attempts_number
        CHECK (attempt_number IN (1, 2, 3)),
    CONSTRAINT ck_reminder_delivery_attempts_state
        CHECK (state IN ('UNKNOWN', 'DELIVERED', 'KNOWN_FAILURE')),
    CONSTRAINT ck_reminder_delivery_attempts_failure_category
        CHECK (failure_category IS NULL OR failure_category IN ('MISSING_CHAT', 'TELEGRAM_REJECTED', 'UNKNOWN_TRANSPORT'))
);
