ALTER TABLE users ADD COLUMN admin BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN manager BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE daily_reports ADD COLUMN department VARCHAR(255);
ALTER TABLE daily_reports ADD COLUMN unit VARCHAR(255);
